name: Buildpack

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - id: setup-pack
        uses: buildpacks/github-actions/setup-pack@v4.9.0
      - run: npm ci
      - run: pack build my-app --builder gcr.io/buildpacks/builder
      - run: docker images
