name: Buildpack

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: docker run --platform linux/arm64/v8 -v /Users/carlhos/.lima/docker/sock/docker.sock:/var/run/docker.sock -v $PWD:/workspace -w /workspace buildpacksio/pack build helloHttp --builder gcr.io/buildpack/builder:latest 
      - run: docker images
